import type { Metadata } from "next";
import { Inter, Plus_Jakarta_Sans } from "next/font/google";
import "./globals.css";
import { Navbar } from "@/components/nav/navbar";
import { ConditionalFooter } from "@/components/footer/conditional-footer";
import { ViewTransition } from "react";
import { ViewTransitionTracker } from "@/components/providers/view-transition-tracker";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const plusJakartaSans = Plus_Jakarta_Sans({
  variable: "--font-heading",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${inter.variable} ${plusJakartaSans.variable}`}>
      <body className="antialiased flex flex-col min-h-screen">
        <ViewTransitionTracker />
        <Navbar />
        <ViewTransition>
          <main className="flex-1">{children}</main>
        </ViewTransition>
        <ConditionalFooter />
      </body>
    </html>
  );
}
