"use client"

import type { Metadata } from "next";
import { Inter, Plus_Jakarta_Sans } from "next/font/google";
import "./globals.css";
import { Navbar } from "@/components/nav/navbar";
import { ConditionalFooter } from "@/components/footer/conditional-footer";
import { useEffect, ViewTransition } from "react";
import { usePathname } from "next/navigation";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const plusJakartaSans = Plus_Jakarta_Sans({
  variable: "--font-heading",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

let prevPath: string | null  = null 

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pathname = usePathname()

  useEffect(() => {
    if(prevPath) {
      document.documentElement.dataset.direction = pathname > prevPath ? "forward" : "back"
    }

    prevPath = pathname

  }, [pathname])

  return (
    <html lang="en" className={`${inter.variable} ${plusJakartaSans.variable}`}>
      <body className="antialiased flex flex-col min-h-screen">
        <Navbar />
        <ViewTransition >
          <main className="flex-1">{children}</main>
        </ViewTransition>
        <ConditionalFooter />
      </body>
    </html>
  );
}
